# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeinanHu
email: 1406062223@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Stay hungry,stay foolish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weinanhu.github.io" # the base hostname & protocol for your site
twitter_username: weinanhu1991
github_username:  weinanhu

# Build settings
markdown: kramdown
